version: '2'
services:
  mvc:
    image: openjdk:8-jdk-alpine
    ports:
      - 8080:8080
    volumes:
      - .:/mvc
    working_dir: /mvc
    command: ./gradlew :modules:mvc:bootRun
    depends_on:
      - mock
    extra_hosts:
     - "mock.soudegesu.com:10.2.0.3"
    networks:
      vpcbr:
        ipv4_address: 10.2.0.2

  mock:
    build:
      context: .
      dockerfile: Dockerfile.mock
    hostname: mock
    volumes:
      - ./mock/lua_file/:/usr/local/openresty/nginx/lua_file
      - ./mock/conf.d/:/usr/local/openresty/nginx/conf.d
      - ./mock/logs/:/usr/local/openresty/nginx/logs
    ports:
      - 9080:80
      - 9443:443
    networks:
      vpcbr:
        ipv4_address: 10.2.0.3

  monitor:
    image: prom/prometheus
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - mvc
    extra_hosts:
     - "web.soudegesu.com:10.2.0.2"
    networks:
      vpcbr:
        ipv4_address: 10.2.0.5

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.2.0.0/16
         gateway: 10.2.0.1
