version: '2'
services:
  mvc:
    image: openjdk:8-jdk-alpine
    expose:
      - 8081
    ports:
      - 8081:8081
    volumes:
      - ./modules/mvc:/mvc
    working_dir: /mvc
    command: ./gradlew bootRun
    depends_on:
      - mock
    extra_hosts:
     - "mock.soudegesu.com:10.2.0.4"
    networks:
      vpcbr:
        ipv4_address: 10.2.0.2

  webflux:
    image: openjdk:8-jdk-alpine
    expose:
      - 8082
    ports:
      - 8082:8082
    volumes:
      - ./modules/webflux:/webflux
    working_dir: /webflux
    command: ./gradlew bootRun
    depends_on:
      - mock
    extra_hosts:
     - "mock.soudegesu.com:10.2.0.4"
    networks:
      vpcbr:
        ipv4_address: 10.2.0.3

  mock:
    build:
      context: .
      dockerfile: Dockerfile.mock
    hostname: mock
    volumes:
      - ./mock/lua_file/:/usr/local/openresty/nginx/lua_file
      - ./mock/conf.d/:/usr/local/openresty/nginx/conf.d
      - ./mock/logs/:/usr/local/openresty/nginx/logs
    expose:
      - 80
    ports:
      - 9080:80
      - 9443:443
    networks:
      vpcbr:
        ipv4_address: 10.2.0.4

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - mvc
      - webflux
    extra_hosts:
     - "mvc.soudegesu.com:10.2.0.2"
     - "webflux.soudegesu.com:10.2.0.3"
    networks:
      vpcbr:
        ipv4_address: 10.2.0.5

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
#    extra_hosts:
#     - "prom.soudegesu.com:10.2.0.5"
    env_file:
      - ./monitor/grafana.env

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.2.0.0/16
         gateway: 10.2.0.1
