server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics,httptrace,threaddump,heapdump
        exclude: flyway

app:
  backend:
    uri: http://mock.soudegesu.com:80
