server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics,httptrace,threaddump,heapdump
        exclude: flyway
  metrics:
    web:
      server:
        auto-time-requests: true

app:
  backend:
    uri: http://mock.soudegesu.com:80